<?php include('header.php')  ?>
<div class="banner-breadcrumb">
    <span class="background-banner"><img src="assets/img/innerPage/breadcums/product.webp" alt=""
            class="img-fluid"></span>
    <div class="banner-tit">
        <h2><span> Shake Grader</span></h2>
    </div>
</div>

<div class="productSec">
    <div class="innerProductDetails">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-md-6">
                    <div class="productImg">
                        <div class="swiper productSwiper">
                            <div class="swiper-wrapper">
                                <?php
                                $nb_elem_per_page = 100;
                                $page = isset($_GET['page']) ? intval($_GET['page'] - 1) : 0;
                                $data = glob("assets/img/products/details/shake-grader/*.*");
                                $number_of_pages = intval(count($data) / $nb_elem_per_page) + 1;
                                foreach (array_slice($data, $page * $nb_elem_per_page, $nb_elem_per_page) as $p) {
                                ?>
                                <div class="swiper-slide"> <img src="<?php echo $p; ?>" alt=""></div>
                                <?php } ?>
                            </div>
                            <div class="swiper-pagination"></div>
                            <div class="swiper-button-prev"></div>
                            <div class="swiper-button-next"></div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12 col-md-6">
                    <div class="productContent">
                        <div class="title-area mb-0">
                            <span class="sub-title">AllVege
                                <span class="shape right">
                                    <span class="dots"></span>
                                </span>
                            </span>
                            <h2 class="sec-title mb-0"> Shake Grader</h2>
                        </div>
                        <div class="desc">
                            <p>The Allround Shake grader from Allvege Process Technologies is designed to grade produce
                                according to square size using four-dimensional grading. The produce is fed into the
                                machine and distributed onto the top sieve. The sieves inside the machine operate with
                                sequential shaking frequencies, allowing the produce to move along the sieve surfaces.
                            </p>

                            <p>The sieve movement is generated by a motor located at the front of the machine. This
                                motor drives a crankshaft, which produces the shaking action of the sieves. The motor is
                                equipped with a computer-controlled frequency inverter, enabling the sieves to operate
                                at multiple sequential frequencies.</p>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>



    <div class="feacture">
        <div class="container">
            <div class="col-12">
                <div class="title-area mb-0">
                    <h2 class="sec-title mb-0">Characteristics</h2>
                </div>

                <div class="feature-list mt-5">
                    <ul class="column-count">
                        <li>
                            <div class="al-step-icon p-relative">
                                <span>
                                    <i class="fa-solid fa-check"></i>
                                </span>
                            </div>
                            Grade produce according to the square size with four-dimensional grading
                        </li>
                        <li>
                            <div class="al-step-icon p-relative">
                                <span>
                                    <i class="fa-solid fa-check"></i>
                                </span>
                            </div>
                            Chutes are included
                        </li>


                        <li>
                            <div class="al-step-icon p-relative">
                                <span>
                                    <i class="fa-solid fa-check"></i>
                                </span>
                            </div>
                            Sieves will be offered separately
                        </li>

                        <li>
                            <div class="al-step-icon p-relative">
                                <span>
                                    <i class="fa-solid fa-check"></i>
                                </span>
                            </div>
                            The sieves in the machine shake in sequential frequencies

                        </li>

                        <li>
                            <div class="al-step-icon p-relative">
                                <span>
                                    <i class="fa-solid fa-check"></i>
                                </span>
                            </div>
                            The frame can be made from painted mild steel or galvanized steel. But the bearings and
                            drive/idle rollers are always made from mild steel
                        </li>
                        <li>
                            <div class="al-step-icon p-relative">
                                <span>
                                    <i class="fa-solid fa-check"></i>
                                </span>
                            </div>
                            The sieves can be changed on the left side/right side of the machine (produce perspective)
                        </li>


                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="tableData bgGrey">
        <div class="container">
            <div class="col-sm-12 col-md-12">
                <div class="title-area mb-0">
                    <h2 class="sec-title mb-0">Specifications</h2>
                </div>
                <div class="table-responsive pt-5 pb-0">
                    <table class="machine-table">
                        <thead>
                            <tr>
                                <th></th>
                                <th>SG 60</th>
                                <th>SG 80</th>
                                <th>SG 120</th>
                                <th>SG 160</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Width of the sieves (in cm)</td>
                                <td>60</td>
                                <td>80</td>
                                <td>120</td>
                                <td>160</td>
                            </tr>
                            <tr>
                                <td>Amount of sieve decks</td>
                                <td>3, 4</td>
                                <td>3, 4, 5</td>
                                <td>3, 4, 5</td>
                                <td>3, 4, 5</td>
                            </tr>
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
    <div class="tableData">
        <div class="container">
            <div class="col-sm-12 col-md-12">
                <div class="title-area mb-0">
                    <h2 class="sec-title mb-0">Options</h2>
                </div>
                <div class="content-responsive pt-5 pb-0">
                    <div class="material-section">

                        <h3 class="section-title">Material and treatment (frame)</h3>
                        <div class="material-row">
                            <div class="material-name">Painted mild steel</div>
                            <div class="material-desc">
                                Frame is made from painted mild steel. The bearings and drive/idle rollers are from mild
                                steel.
                                The doors are made from painted mild steel
                            </div>
                        </div>
                        <div class="material-row">
                            <div class="material-name">Galvanized steel</div>
                            <div class="material-desc">
                                Frame is made from galvanized steel. The bearings and drive/idle rollers are from mild
                                steel.
                                The doors are made from stainless steel AISI304
                            </div>
                        </div>

                        <h3 class="section-title">Sieve changing side</h3>
                        <div class="material-row">
                            <div class="material-name">Left</div>
                            <div class="material-desc">
                                The sieves can be changed on the left side of the machine (produce perspective)
                            </div>
                        </div>
                        <div class="material-row">
                            <div class="material-name">Right</div>
                            <div class="material-desc">
                                The sieves can be changed on the right side of the machine (produce perspective)
                            </div>
                        </div>

                        <h3 class="section-title">Doors</h3>
                        <div class="material-row">
                            <div class="material-name">Doors</div>
                            <div class="material-desc">
                                Doors are included on the sides of the machine
                            </div>
                        </div>

                        <h3 class="section-title">Electrical control</h3>
                        <div class="material-row">
                            <div class="material-name">No electric</div>
                            <div class="material-desc">
                                Motors and necessary sensors
                            </div>
                        </div>
                        <div class="material-row">
                            <div class="material-name">Stand-alone</div>
                            <div class="material-desc">
                                Motors, necessary sensors and control panel with HMI.
                                The length of the cable is 5, 10, 15 or 20 meter
                            </div>
                        </div>
                        <div class="material-row">
                            <div class="material-name">Central control in line</div>
                            <div class="material-desc">
                                Motors and necessary sensors
                            </div>
                        </div>

                        <h3 class="section-title">Material and treatment (electrical panel)</h3>
                        <div class="material-row">
                            <div class="material-name">Painted mild steel</div>
                            <div class="material-desc">
                                The electrical panel is made from painted mild steel
                            </div>
                        </div>
                        <div class="material-row">
                            <div class="material-name">Stainless steel</div>
                            <div class="material-desc">
                                The electrical panel is made from stainless steel AISI304
                            </div>
                        </div>

                        <h3 class="section-title">Sieves</h3>
                        <div class="material-row">
                            <div class="material-name">Sieves</div>
                            <div class="material-desc">
                                Sieves will be offered separatly
                            </div>
                        </div>

                        <h3 class="section-title">Material and treatment (subframe)</h3>
                        <div class="material-row">
                            <div class="material-name">Painted mild steel</div>
                            <div class="material-desc">
                                It is made of painted mild steel
                            </div>
                        </div>
                        <div class="material-row">
                            <div class="material-name">Galvanized steel</div>
                            <div class="material-desc">
                                It is made of galvanized mild steel
                            </div>
                        </div>

                        <h3 class="section-title">Height of subframe</h3>
                        <div class="material-row">
                            <div class="material-name">Height of subframe</div>
                            <div class="material-desc">
                                0 – 7 meters
                            </div>
                        </div>

                        <h3 class="section-title">Product collection – chute set</h3>
                        <div class="material-row">
                            <div class="material-name">Chute set</div>
                            <div class="material-desc">
                                Chutes are included
                            </div>
                        </div>

                        <h3 class="section-title">Cleaning – double sieve cleaner</h3>
                        <div class="material-row">
                            <div class="material-name">Double sieve cleaner</div>
                            <div class="material-desc">
                                A double sieve cleaner is included
                            </div>
                        </div>

                        <h3 class="section-title">Bag holder</h3>
                        <div class="material-row">
                            <div class="material-name">Bag holder</div>
                            <div class="material-desc">
                                A bag holder is included to fill the bags
                            </div>
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>










</div>

<?php include('footer.php')  ?>